name: Plugin Code Check

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # 使用点 (.) 扫描当前根目录下所有文件，避免文件夹名称匹配导致的报错
      - name: Run PHPCBF (Auto Fix)
        run: ./vendor/bin/phpcbf --standard=phpcs.xml . || true

      - name: Run PHPCS
        run: ./vendor/bin/phpcs --standard=phpcs.xml .